### ISSUE TITLE
Rozdzielenie seederów na prod i local

### ISSUE THREAD

**Issue by DarHorr** [Dainc007/project1#15]
Do rozdzielenia struktura katalogów seederów w zależności od środowiska aplikacji.

**Wyróżnione powinny być dwa typy seederów:**
- local - seedery wykonujące się tylko na środowisku typu *local*
- prod - seedery wykonujące się na środowisku *local* oraz *production* 

Oba seedery powinny być wywoływane w DatabaseSeeder z uwzględnieniem warunków na typ środowiska. 
Przykładowa struktura katalogów:
<img width="319" alt="image" src="https://user-images.githubusercontent.com/130851187/232586145-2afe8400-6ac1-4374-9b63-c2e0bef0a3a5.png">

Na środowisku *local* seedery powinny wykonywać się w kolejności: *prod*, *local*

**Comment by Dainc007** [comment]
Dobry pomysł

**Comment by DarHorr** [comment]
Tworzenie seederów `php artisan make:seeder prod/CompetitionSeeder`
