### ISSUE TITLE
Tworzenie Rozgrywek

### ISSUE THREAD

**Issue by Dainc007** [Dainc007/project1#8]
dodajemy nowy element nawigujący do rozgrywek (jeśli user na odpowiednie uprawnienia do Tworzenia rozgrywek)
![image](https://user-images.githubusercontent.com/62115633/232293790-2f75f810-f94c-49b5-b84a-bc69925c2120.png)

Po przejsciu do zakładki całość będzie na razie prostym CRUDem do Tworzenia Rozgrywek na razie tylko z polami takimi jak id oraz name

**Comment by Dainc007** [comment]
@DarHorr  jak coś to w CompetitionController zjadło Ci returny w metodach

**Comment by DarHorr** [comment]
@Wojtazzzz Z tego co widzę jest okej 

https://github.com/Dainc007/project1/blob/develop/app/Http/Controllers/CompetitionController.php

**Comment by Wojtazzzz** [comment]
@DarHorr złą osobę oznaczyłeś :D chyba chodziło o @Dainc007

**Comment by Dainc007** [comment]
Tak o mnie, już wyjaśnione, byłem przekonany, że mam najnowsze zmiany. Nie miałem 👍
